"""empty message

Revision ID: 1d0a803edbc0
Revises: bd322c2e5c7b
Create Date: 2024-10-09 02:52:24.368434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0a803edbc0'
down_revision = 'bd322c2e5c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('average_rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
