"""empty message

Revision ID: bd322c2e5c7b
Revises: e259f32dadec
Create Date: 2024-10-09 02:50:54.343775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd322c2e5c7b'
down_revision = 'e259f32dadec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('average_rating')
        batch_op.drop_column('status')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
